### PR TITLE
Upgrade CodeNarc to 1.6.1

### LINKED ISSUE #26: Upgrade CodeNarc to 1.5
CodeNarc 1.5 has been released on 24 Nov 2019 (read [changelog](https://github.com/CodeNarc/CodeNarc/blob/master/CHANGELOG.md#version-15----nov-2019)).

Could you bump version from 1.4 to 1.5?

### PR DESCRIPTION
**Pull request by goober**
This change will refactor the rule converter to be compatible with the new markdown based documentation
from the upstream CodeNarc project.

Note that it is still a work in progress so it has some rough edges. However, I would love some feedback at this early stage to validate that I am on the right way.

Fixes #26

### CODE REVIEW

**Comment by goober** [comment]
FYI @TobiX

**Comment by TobiX** [comment]
Ohhhh, nice! Thanks for starting this! Will take a more detailed look later, but that looks roughly like I envisioned it ❤️

**Comment by goober** [comment]
The parser can be heavily simplified once https://github.com/CodeNarc/CodeNarc/pull/640 har been published. Then all parameters, default values and description can be parsed directly from the documentation and not relying on reflection.

**Comment by TobiX** [comment]
So I had some time to review and test this - Since it looks & works fine, I went ahead and merged it 👍 

Thanks again for your contribution!

**Comment by goober** [comment]
Thank you, just a follow-up question, is there any blockers that you see to upgrade codenarc to the latest 2.x version after this pr had been released?

**Comment by TobiX** [comment]
@goober No, not really. Should be pretty straightforward after your changes...

**Pull request merged**
