### PR TITLE
Replace deprecated RulesProfile for scanner-side operations

### PR DESCRIPTION
**Pull request by Hydragyrum**
This should work in Sonarqube 7.6+

I'm a bit unsure about the validity of one of the tests, I left it Ignored for the moment to request advice.

### CODE REVIEW

**Comment by Hydragyrum** [comment]
Forums seem to want to replace the RulesProfile by an ActiveRules set on the scanner side, as RulesProfile is a Server-Side only component now.

**Comment by Hydragyrum** [comment]
Screenshot on a sample project
image

**Comment by Hydragyrum** [comment]
Of course they changed the unit testing API in 7.5

**Comment by TobiX** [comment]
Merged while fixing merge conflict.

**Pull request closed without merging**
