### PR TITLE
Replace rules profile for SonarQube 7.5+

### PR DESCRIPTION
**Pull request by Hydragyrum**
Since the testing API changed in 7.5, builds were failing.  Same changes as #4 otherwise

### CODE REVIEW

**Comment by TobiX** [comment]
Thanks, but for now I will politely decline this change because I want this plugin to stay compatible with SonarQube 6.7 for a little while longer...

**Comment by CCFenner** [comment]
I would vote for LTS (6.7.5) compatibility, as we use it heavily.

**Comment by Hydragyrum** [comment]
Sure, the only real change is that the internal apis for testing have changed somewhat. They probably aren't particularily stable at the moment and we should wait for the next LTS to fix them.

**Comment by TobiX** [comment]
I commited a horrible kludge to get around this class incompatibility, so I consider this solved for now.

**Pull request closed without merging**
